spring:
  data:
    web:
      pageable:
        default-page-size: 30
        max-page-size: 50
    mongodb:
      port: 27017
      uri: mongodb://mongo/dnipro
      repositories.enabled: true
      auto-index-creation: true
